name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: .env 파일 생성
        run: |
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env
          echo "AWS_TABLE_NAME_WINPROCS=${{ secrets.AWS_TABLE_NAME_WINPROCS }}" >> .env
          echo "AWS_TABLE_NAME_USERINFO=${{ secrets.AWS_TABLE_NAME_USERINFO }}" >> .env
          echo "AWS_TABLE_NAME_USERUSAGE=${{ secrets.AWS_TABLE_NAME_USERUSAGE }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env

      - name: 패키지 설치
        run: npm ci

      - name: 빌드
        run: npm run build